apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: trivy-scan
spec:
  workspaces:
    - name: source
  steps:
    - name: trivy
      image: aquasec/trivy:latest
      script: |
        trivy image \
        image-registry.openshift-image-registry.svc:5000/jbanday100-dev/python-openshift-cicd:latest \
        --severity HIGH,CRITICAL \
        --exit-code 0
