apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: python-openshift-cicd-
spec:
  pipelineRef:
    name: python-openshift-cicd-pipeline
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: ssh-directory
      emptyDir: {}
